- name: Enable RPM Fusion
#https://obsproject.com/wiki/install-instructions#fedora-installation-unofficial
  dnf: 
        name: 
                - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

- name: Install packages
  dnf: 
    name:
      - snapd
      - htop 
      - terminator
      - powertop
      - slack
      - gnome-tweak-tool
      - python3
      - tlp
      - tlp-rdw
      - gimp
      - obs-studio
    state: present

- name: Install the spotify flatpak
  flatpak:
    name:  https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref
    state: present

- name: Install chrome
  dnf:
        name: 
                - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        state: present
  #Install sublime text
  #Install insync