- name: Enable the RPM Fusion repository
  dnf:
    #Reference https://serverfault.com/questions/1021744/how-to-install-rpm-fusion-repository-with-ansible-on-fedora-32-server-virtual-ma
    name: 
      - "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'
#- name: Install snapd
#  dnf: 
#    name: snapd

#- name: Enable snapd service
#  systemd:
#    state: started
#    name: snapd.socket

- name: Install packages
  dnf: 
    name:
      #- snapd
      - htop #This works
      - terminator #This works
      - powertop #This works
      - slack #This works
      - gnome-tweak-tool #This works
      - python3 #This works
      - tlp #This works
      - tlp-rdw #This works
      - gimp #This works
    state: present

#- name: Install snapd packages
#  snap:
#    name:
#      - obs-studio
#      - spotify
#    state: present

- name: Install chrome
  dnf:
        name: 
                - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        state: present
  #Install sublime text
  #Install insync