- name: Enable the RPM Fusion repository
  dnf:
    #Reference https://serverfault.com/questions/1021744/how-to-install-rpm-fusion-repository-with-ansible-on-fedora-32-server-virtual-ma
    name: 
      - "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Install packages
  dnf: 
    name:
      - htop
      - terminator
      - powertop
      - slack
      - gnome-tweak-tool
      - python3
      - tlp
      - tlp-rdw
      - gimp
      - "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
    state: present

#Install Solarized Dark GNOME Theme from GitHub
#- git:
    #repo: https://github.com/rtlewis88/rtl88-Themes/tree/Solarized-Dark-GNOME-Shell-COLORS/Solarized-Dark-Red-GNOME-Shell
#    repo: https://github.com/rtlewis88/rtl88-Themes.git
#    dest: /tmp/rtl88-Themes
#
#- name: Copy Solarized Dark GNOME Theme from tmp to themes
#  copy:
#    src: /tmp/Solarized-Dark-Red-GNOME-Shell
#    dest: /usr/share/themes
#
#- name: Remove flat-remix from tmp
#  win_file:
#    path: /tmp/flat-remix
#    state: absent

- name: Download flat-remix repo with wget
  shell: "git clone /tmp/flat-remix https://github.com/daniruiz/flat-remix.git"
#Fix so that I authenticate to github before trying to d/l the repo
#- git:
    #repo: https://github.com/daniruiz/flat-remix/tree/master/Flat-Remix-Blue-Dark
#    repo: https://github.com/daniruiz/flat-remix.git
#    dest: /tmp/flat-remix
#    separate_git_dir: /tmp/flat-remix.git

#- name: Copy Flat-remix-blue-dark icons from tmp to icons
#  copy:
#    src: /tmp/Flat-Remix-Blue-Dark
#    dest: /usr/share/icons
#
- name: Install spotify flatpak
  flatpak:
    name: https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
    state: present
 
- name: Add sublime-text repository
  yum_repository:
    name: sublime-text.repo
    description: Sublime text repo
    baseurl: https://download.sublimetext.com/rpm/stable/{{ansible_architecture}}
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    state: present

- name: Install sublime-text
  dnf:
    name:
      - sublime-text
    state: present
#Install insync