#- name: Enable the RPM Fusion repository
#  dnf:
#    name: 
#      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
#      - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm
#    state: present
#  name: subscription-manager repos --enable "codeready-builder-for-rhel-8-$(uname -m)-rpms"
#
- name: Install packages
  dnf: 
    name:
      #- snapd
      - htop #This works
      - terminator #This works
      - powertop #This works
      - slack #This works
      - gnome-tweak-tool #This works
      - python3 #This works
      - tlp #This works
      - tlp-rdw #This works
      - gimp
      #- obs-studio
    state: present

- name: Install the spotify flatpak
  flatpak:
    name:  https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref
    state: present

- name: Install chrome
  dnf:
        name: 
                - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        state: present
  #Install sublime text
  #Install insync