- name: Enable the RPM Fusion repository
  dnf:
    #Reference https://serverfault.com/questions/1021744/how-to-install-rpm-fusion-repository-with-ansible-on-fedora-32-server-virtual-ma
    name: 
      - "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Install packages
  dnf: 
    name:
      - htop
      - terminator
      - powertop
      - slack
      - gnome-tweak-tool
      - python3
      - tlp
      - tlp-rdw
      - gimp
      - "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
    state: present
 
- name: Add sublime-text repository
  yum_repository:
    name: sublime-text.repo
    description: Sublime text repo
    baseurl: https://download.sublimetext.com/rpm/stable/{{ansible_architecture}}
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    state: present

- name: Install sublime-text
  dnf:
    name:
      - sublime-text
    state: present
#Install insync