tasks:
  - name: Enable Flathub
    become: yes
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  
  - name: Install Fractal
    become: yes
      command: flatpak install --assumeyes flathub org.gnome.Fractal

- name: Enable RPM Fusion
  #https://obsproject.com/wiki/install-instructions#fedora-installation-unofficial
  dnf: 
        name: 
                - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

- name: Install packages
  dnf: 
    name:
      - snapd
      - htop 
      - terminator
      - powertop
      - slack
      - gnome-tweak-tool
      - python3
      - tlp
      - tlp-rdw
      - gimp
    state: present

- name: Install Spotify
  become: yes
  command: flatpak install --assumeyes flathub com.spotify.Client

- name: Install OBS Project
  #https://obsproject.com/wiki/install-instructions#fedora-installation-unofficial
  dnf:
          - obs-studio

- name: Install chrome
  dnf: 
        name: 
                - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        state: present

- name: Remove packages
      become: yes
      package:
              name: rhythmbox
      state: absent
  
  #Install sublime text
  #Install insync