- name: Enable the RPM Fusion repository
  dnf:
    #Reference https://serverfault.com/questions/1021744/how-to-install-rpm-fusion-repository-with-ansible-on-fedora-32-server-virtual-ma
    name: 
      - "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Install packages
  dnf: 
    name:
      - htop
      - terminator
      - powertop
      - slack
      - gnome-tweak-tool
      - python3
      - tlp
      - tlp-rdw
      - gimp
      - "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
    state: present

- name: Install spotify flatpak
  flatpak:
    name:
      - "https://flathub.org/repo/appstream/com.spotify.Client.flatpakref"
    state: present

#- name: Import gpg key for sublime text
#Reference https://computingforgeeks.com/how-to-install-sublime-text-3-on-centos-rhel-8/
- rpm_key:
    state: present
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

- name: Add repository
  yum_repository:
    name: sublime-text.repo
    description: Sublime text repo
    baseurl: https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo

- name: Install sublime-text
  dnf:
    name:
      - sublime-text
    state: present

#- name: Install chrome
#  dnf:
#        name: 
#                - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
#        state: present
  #Install insync