#Install Solarized Dark GNOME Theme from GitHub
#- git:
    #repo: https://github.com/rtlewis88/rtl88-Themes/tree/Solarized-Dark-GNOME-Shell-COLORS/Solarized-Dark-Red-GNOME-Shell
#    repo: https://github.com/rtlewis88/rtl88-Themes.git
#    dest: /tmp/rtl88-Themes
#
#- name: Copy Solarized Dark GNOME Theme from tmp to themes
#  copy:
#    src: /tmp/Solarized-Dark-Red-GNOME-Shell
#    dest: /usr/share/themes
#
#Research block command (block and rescue and always)
- name: Delete directory flat-remix
  file:
    path: /tmp/flat-remix
    state: absent

- name: Create directory flat-remix
  file:
    path: /tmp/flat-remix
    state: directory

- name: Download flat-remix repo with wget
  shell: "git clone https://github.com/daniruiz/flat-remix.git /tmp/flat-remix"

- name: Remove Flat-Remix-Blue-Dark directory from icons
  file:
    path: /usr/share/icons/Flat-Remix-Blue-Dark/
    state: absent

- name: Move Flat-Remix-Blue-Dark with shell command
  shell: "cp -R /tmp/flat-remix/Flat-Remix-Blue-Dark/ /usr/share/icons"

- name: Remove Flat-Remix-Red-Dark directory from icons
  file:
    path: /usr/share/icons/Flat-Remix-Red-Dark/
    state: absent

- name: Move Flat-Remix-Red-Dark with shell command
  shell: "cp -R /tmp/flat-remix/Flat-Remix-Red-Dark/ /usr/share/icons"